export const HOLY_NAME_SUGGESTIONS = Object.freeze([
  'Maria',
  'Giuse',
  'Gioan',
  'Anna',
  'Antôn',
  'Phêrô',
  'Phaolô',
  'Têrêsa',
  'Catarina',
  'Phanxicô',
  'Đa Minh',
  'Inhaxiô',
  'Micae',
  'Tôma',
  'Luca',
  'Mátthêu',
  'Mác-cô',
  'Anrê',
  'Giacôbê',
  'Bênêđictô',
  'Clara',
  'Agnês',
  'Monica',
  'Elisabeth',
  'Rita',
  'Cecilia',
])

export const BIRTH_PLACE_SUGGESTIONS = Object.freeze([
  'Tp. Hồ Chí Minh',
  'Hà Nội',
  'Hải Phòng',
  'An Giang',
  'Bà Rịa - Vũng Tàu',
  'Bắc Giang',
  'Bắc Kạn',
  'Bạc Liêu',
  'Bắc Ninh',
  'Bến Tre',
  'Bình Định',
  'Bình Dương',
  'Bình Phước',
  'Bình Thuận',
  'Cà Mau',
  'Cao Bằng',
  'Cần Thơ',
  'Đà Nẵng',
  'Đắk Lắk',
  'Đắk Nông',
  'Điện Biên',
  'Đồng Nai',
  'Đồng Tháp',
  'Gia Lai',
  'Hà Giang',
  'Hà Nam',
  'Hà Tĩnh',
  'Hải Dương',
  'Hậu Giang',
  'Hòa Bình',
  'Hưng Yên',
  'Khánh Hòa',
  'Kiên Giang',
  'Kon Tum',
  'Lai Châu',
  'Lạng Sơn',
  'Lào Cai',
  'Lâm Đồng',
  'Long An',
  'Nam Định',
  'Nghệ An',
  'Ninh Bình',
  'Ninh Thuận',
  'Phú Thọ',
  'Phú Yên',
  'Quảng Bình',
  'Quảng Nam',
  'Quảng Ngãi',
  'Quảng Ninh',
  'Quảng Trị',
  'Sóc Trăng',
  'Sơn La',
  'Tây Ninh',
  'Thái Bình',
  'Thái Nguyên',
  'Thanh Hóa',
  'Thừa Thiên Huế',
  'Tiền Giang',
  'Trà Vinh',
  'Tuyên Quang',
  'Vĩnh Long',
  'Vĩnh Phúc',
  'Yên Bái',
])

export const SUGGESTION_CATEGORIES = Object.freeze([
  'holy_name',
  'birth_place',
  'parish',
  'priest',
  'diocese',
] as const)

export type SuggestionCategory = (typeof SUGGESTION_CATEGORIES)[number]
